---
name: Build and Optionally Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Only
      uses: docker/bake-action@v5
      with:
        files: |
          ./docker-bake.hcl
        targets: build
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v5
      with:
        images: hutchic/${{ github.event.repository.name }}
        tags: |
          type=semver,pattern={{version}},value=${{ steps.release.outputs.release-version }}
          type=ref,event=branch
          type=sha
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build & Push
      uses: docker/bake-action@v5
      with:
        push: 'true'
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build
